### ISSUE TITLE
Insert <br /> tag to force a line break in the main page heading

### ISSUE THREAD

**Issue by WimTeuling** [SeanHLam/metrolics_repo#24]
https://github.com/SeanHLam/metrolics_repo/blob/d2d3ad31d13360b291b4e56f9edd17791b79a732/index.html#L46-L49

```
<h1 class="intro">Hey guys! This is the Metrolics theme. <br/>
      It sports a responsive layout with a mobile layout.
</h1>
```

**Comment by NaincyKumariKnoldus** [comment]
Hey @WimTeuling Can I add this please?

**Comment by WimTeuling** [comment]
Yes, of course! You as team members decide which issues to resolve.
