### ISSUE TITLE
Syntax errors in html code

### ISSUE THREAD

**Issue by WimTeuling** [SeanHLam/metrolics_repo#31]
https://github.com/SeanHLam/metrolics_repo/blob/d2d3ad31d13360b291b4e56f9edd17791b79a732/index.html#L180
https://github.com/SeanHLam/metrolics_repo/blob/d2d3ad31d13360b291b4e56f9edd17791b79a732/index.html#L193

...and others. Please check.

**Comment by NaincyKumariKnoldus** [comment]
Hey @WimTeuling Can I do this please?

**Comment by WimTeuling** [comment]
Fix anything you want. Do communicate this with your team member(s).

**Comment by NaincyKumariKnoldus** [comment]
Which team members @WimTeuling ?
